# Generated by Django 2.1 on 2019-05-06 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('allowed_format', models.ManyToManyField(to='quotation.Format')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('type_of_service', models.IntegerField(choices=[(1, 'Business To Business'), (2, 'Hand To Hand'), (3, 'Direct Mail'), (4, 'Residential Homes'), (5, 'Shared Distribution'), (6, 'Consultation Distribution')], default=1)),
                ('number_of_boxes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 or more'), (5, 'N/A')], default=1)),
                ('type_of_media', models.IntegerField(choices=[(1, 'Flyer'), (2, 'Leaflet'), (3, 'Folded Leaflet'), (4, 'Other')], default=1)),
                ('require_collection', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1)),
                ('quantity_of_flyers', models.IntegerField(null=True)),
                ('title_of_media', models.CharField(max_length=255, null=True)),
                ('campaign_details', models.TextField(max_length=255)),
                ('agreed_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('campaign_start_date', models.DateField(null=True)),
                ('campaign_finish_date', models.DateField(null=True)),
                ('special_instruction', models.TextField()),
                ('printing_required', models.BooleanField(default=False)),
                ('pages', models.IntegerField(choices=[(1, 'Single Sided'), (2, 'Double Sided'), (3, '2 Pages'), (4, '4 Pages'), (5, '6 Pages'), (6, '8 Pages'), (7, '10 Pages'), (8, '12 Pages')], null=True)),
                ('page_orientation', models.IntegerField(choices=[(1, 'Portrait'), (2, 'Landscape')], null=True)),
                ('colours', models.IntegerField(choices=[(1, '1/0-coloured Black'), (2, '2/0-coloured Black + Pantone'), (3, '2/0-coloured Black + Gold'), (4, '4/0-coloured CMYK')], null=True)),
                ('processing', models.IntegerField(choices=[(1, 'Trimming'), (2, 'Trimming Corner Rounded')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_manager', models.ForeignKey(limit_choices_to={'accountant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(to='core.Attachments')),
                ('gsm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.GSM')),
                ('page_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.Format')),
            ],
        ),
        migrations.CreateModel(
            name='TargetArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('households', models.IntegerField()),
                ('geo_json', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='target_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.TargetArea'),
        ),
    ]
