# Generated by Django 2.1 on 2019-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='target_postcodes',
            field=models.ManyToManyField(to='core.Postcodes'),
        ),
    ]
