# Generated by Django 2.1 on 2019-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_target_postcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Business To Business'), (2, 'Hand To Hand'), (3, 'Direct Mail'), (4, 'Residential Homes'), (5, 'Shared Distribution'), (6, 'Consultation Distribution')], default=1),
        ),
    ]
