# Generated by Django 2.1 on 2019-05-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
    ]
