# Generated by Django 2.1 on 2019-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='issued_date',
            field=models.DateTimeField(null=True),
        ),
    ]
