# Generated by Django 2.1 on 2019-05-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_quotation_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Reviewed'), (3, 'Accepted')], default=1),
        ),
    ]
