# Generated by Django 2.1 on 2019-05-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0006_auto_20190508_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='assigned_user',
            field=models.ForeignKey(limit_choices_to={'staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
