# Generated by Django 2.1 on 2019-05-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='quotation.Quotation'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.TargetArea'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='gsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.GSM'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='page_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.Format'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.Quotation'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_company', to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_project', to='projects.Project'),
        ),
    ]
