# Generated by Django 2.1 on 2019-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_auto_20190507_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_postcodes',
            field=models.ManyToManyField(related_name='target_postcodes', to='core.Postcodes'),
        ),
    ]
