# Generated by Django 2.1 on 2019-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_target_postcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agreed_cost',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.ManyToManyField(null=True, to='core.Attachments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='campaign_details',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='campaign_finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='campaign_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_boxes',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 or more'), (5, 'N/A')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='require_collection',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='special_instruction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_postcodes',
            field=models.ManyToManyField(null=True, related_name='target_postcodes', to='core.Postcodes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_media',
            field=models.IntegerField(choices=[(1, 'Flyer'), (2, 'Leaflet'), (3, 'Folded Leaflet'), (4, 'Other')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_service',
            field=models.IntegerField(choices=[(1, 'Business To Business'), (2, 'Hand To Hand'), (3, 'Direct Mail'), (4, 'Residential Homes'), (5, 'Shared Distribution'), (6, 'Consultation Distribution')], default=1, null=True),
        ),
    ]
