# Generated by Django 2.1 on 2019-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190507_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_client_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hide_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='time_spent',
            field=models.DurationField(),
        ),
    ]
