# Generated by Django 2.1 on 2019-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190507_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Completed'), (4, 'Awaiting Payment'), (5, 'Suspended'), (6, 'Cancelled')], default=1),
        ),
    ]
