# Generated by Django 2.1 on 2019-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingorder',
            name='priority',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2),
        ),
    ]
