# Generated by Django 2.1 on 2019-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190507_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
    ]
