# Generated by Django 2.1 on 2019-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190507_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
