# Generated by Django 2.1 on 2019-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcodes',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=13)),
                ('area', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=2)),
                ('sector', models.CharField(max_length=1)),
                ('locality', models.CharField(db_column='Locality', max_length=64)),
                ('residential', models.CharField(
                    db_column='Residential', max_length=11)),
                ('business', models.CharField(db_column='Business', max_length=8)),
                ('total', models.CharField(db_column='Total', max_length=9)),
            ],
            options={
                'db_table': 'postcodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
