# Generated by Django 2.1 on 2019-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='postcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
