# Generated by Django 2.1 on 2019-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190507_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
