# Generated by Django 2.1 on 2019-05-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190507_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_user', to='accounts.Clients'),
        ),
    ]
